### ISSUE TITLE
VS Mac 8.1 support

### ISSUE THREAD

**Issue by mrward** [mrward/monodevelop-template-creator-addin#5]
Originally from:

https://developercommunity.visualstudio.com/content/problem/612753/method-not-found-string-monodevelopidedesktopservi.html

“Method not found: string MonoDevelop.Ide.DesktopService.GetMimeTypeForUri(string)”

**Comment by mrward** [comment]
Fixed in commit eed55c4f40f146eaeea63305e203e58da9e81a12

**Comment by iamlawrencev** [comment]
Will there be an .mpack file of the 0.5-monodevelop-8.1 release?

**Comment by mrward** [comment]
The .mpack is available from the monodevelop addin server:

http://addins.monodevelop.com/Project/Index/305

Also published to my own addin server:

https://github.com/mrward/monodevelop-addins/blob/gh-pages/8.1/MonoDevelop.TemplateCreator_0.5.mpack
