### ISSUE TITLE
Unable to create template.json file.

### ISSUE THREAD

**Issue by DannyBloky** [mrward/monodevelop-template-creator-addin#6]
Unable to create template.json file.
Method not found: System.Threading.Tasks.Task`1<MonoDevelop.Ide.Gui.Document> MonoDevelop.Ide.Gui.Workbench.OpenDocument(MonoDevelop.Core.FilePath,MonoDevelop.Projects.Project,bool)

I don't know if I'm doing something wrong but I get this error every time I want to create a template of my project.

**Comment by mrward** [comment]
Which version of VS Mac do you have and which version of the template creator addin?

My guess is that you are not using the latest template creator addin 0.5 in VS Mac 8.2. The Extensions Manager in VS Mac should have the latest 0.5 version to install.

There were some breaking API changes in VS Mac 8.1 which broke the addin.

**Comment by DannyBloky** [comment]
Hi,

I have Visual studio for Mac Community: version 8.2.4
Template creator version 0.4.  I don't see the 0.5 version.
So maybe you haven't release it yet.

**Comment by mrward** [comment]
Version 0.5 was published in June.

http://addins.monodevelop.com/Project/Index/305

**Comment by mrward** [comment]
The main problem seems to be that the addin server does not always update the list of addins for later versions. This is not something I can fix.

**Comment by mrward** [comment]
I have published it explicitly for VS Mac 8.2.5 and it seems to be available for that version using the addin url https://addins.monodevelop.com/Beta/Mac/8.2.5/main.mrep
