### ISSUE TITLE
Solution generation error

### ISSUE THREAD

**Issue by MBrekhof** [mrward/monodevelop-template-creator-addin#7]
Hi
I'm trying to get a custom solution template up and running, I encounter a problem that I would like some feedback on.
The template (attached) is based on a starter Xamarin Forms solution. When creating a new solution I get an error (screenshot attached) and I get a solution that somehow has two solution files (.sln).

Probably I have something wrong in the template but I have no clue as to what. Any help appreciated.

regards
Martin

 
[template.json.txt](https://github.com/mrward/monodevelop-template-creator-addin/files/3835165/template.json.txt)
<img width="603" alt="Screenshot 2019-11-12 at 09 48 23" src="https://user-images.githubusercontent.com/13586354/68656410-0cd4d580-0532-11ea-902d-c9d19ea3c73d.png">
<img width="236" alt="Screenshot 2019-11-12 at 09 48 50" src="https://user-images.githubusercontent.com/13586354/68656417-0fcfc600-0532-11ea-92d0-01f027999712.png">

**Comment by MBrekhof** [comment]
Just in case it matters, when I choose not to create a project directory in the solution directory (screenshot) I get the following error: ..sln already exists
<img width="605" alt="Screenshot 2019-11-12 at 11 30 03" src="https://user-images.githubusercontent.com/13586354/68665455-5b8a6b80-0542-11ea-93bb-7a0c88e13942.png">
 (screenshot)
<img width="899" alt="Screenshot 2019-11-12 at 11 29 44" src="https://user-images.githubusercontent.com/13586354/68665405-47df0500-0542-11ea-9c9b-f7ae79f33060.png">

**Comment by mrward** [comment]
I tried to reproduce some of the problems you are seeing and apart from the duplicate sln file I could not. I created a Blank Forms project and then generated a template for that.

To fix the .sln file you can exclude it. By default the template engine copies all files that exist in the parent directory of the template.json file.

```
 "sources": [
   {
     "modifiers": [
       {
         "exclude": [
			".vs/**/*",
			"*.sln"
         ]
       }
     ]
  
```

The other problems I could not reproduce from the template itself.

The sln file already exists is something that happens in VS Mac if you try to add a new Blank Forms project to an existing solution. This is a known bug in VS Mac. Not sure if that is what you are doing or not here.

**Comment by MBrekhof** [comment]
Hi Matt
excluding the *.sln did work, I extended the list somewhat (.git, .mfractor etc.) and it looks like all my problems are solved.
Thanks
