### ISSUE TITLE
Unable to create Template

### ISSUE THREAD

**Issue by mharrisonbit** [mrward/monodevelop-template-creator-addin#8]
I get the following error when I try to create a template on VS for mac. I downloaded the latest version of template creator from http://addins.monodevelop.com/Project/Index/305. I am running 8.4.4 build 91. 
I get this error when I right click on any project and try to create the template.
Method not found: System.Threading.Tasks.Task`1<MonoDevelop.Ide.Gui.Document> MonoDevelop.Ide.Gui.Workbench.OpenDocument(MonoDevelop.Core.FilePath,MonoDevelop.Projects.Project,bool)

**Comment by mrward** [comment]
Which version do you have installed?

With Template Creator 0.5 I cannot reproduce this problem with VS Mac 8.4.4.

The error looks like the one reported in issue #6 which can happen in older versions of the Template Creator.

**Comment by mrward** [comment]
The only problem I can see is that the addin server has version 0.4 published not 0.5 for VS Mac 8.4.4. The addin server does not seem to make addins available to later versions most of the time, which is a known problem with the server as far as I am aware.

I have published Template Creator 0.5 for VS Mac 8.4.4 now.

**Comment by mharrisonbit** [comment]
I downloaded the .5 beta version for monodevelop 8.4.4 for mac.

**Comment by mharrisonbit** [comment]
well I restarted VS again and now it works. I do apologize and thank you for the wonderful extension. I will close this out. You have a wonderful day.

**Comment by mrward** [comment]
Thanks for letting me know 👍
